### ISSUE TITLE
ModuleNotFoundError on import

### ISSUE THREAD

**Issue by vilhelmen** [CrazyPython/svgmanip#3]
I think the packaging may be messed up? I tried installing the latest version from git and got the same error.

```
will:Ganymede:~% python3 --version
Python 3.7.5
will:Ganymede:~% pip3 --version
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
will:Ganymede:~% pip3 install svgmanip
Collecting svgmanip
  Using cached https://files.pythonhosted.org/packages/f6/20/92ef819c8588372d588d3e20366d62fc09b3b26ef6040c27313258266815/svgmanip-0.0.6.tar.gz
Collecting svgutils
  Using cached https://files.pythonhosted.org/packages/79/da/4f7a31a55c247e304a338716e75d761f3dc9b50b220fcfaad7398668367e/svgutils-0.3.1-py2.py3-none-any.whl
Collecting mpmath
  Using cached https://files.pythonhosted.org/packages/ca/63/3384ebb3b51af9610086b23ea976e6d27d6d97bf140a76a365bd77a3eb32/mpmath-1.1.0.tar.gz
Collecting ensure
  Using cached https://files.pythonhosted.org/packages/17/97/ab76be5534c7ff86cab6629fe7c258bc6c3bc99f6b8ed5b626eb8413453c/ensure-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: lxml in /usr/local/lib/python3.7/site-packages (from svgutils->svgmanip) (4.3.4)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/site-packages (from ensure->svgmanip) (1.12.0)
Building wheels for collected packages: svgmanip, mpmath
  Building wheel for svgmanip (setup.py) ... done
  Created wheel for svgmanip: filename=svgmanip-0.0.6-py2.py3-none-any.whl size=1456 sha256=519dfb752fb69fa6577277f5b8ad3a6efe4e90b163734e488275b85311d822ab
  Stored in directory: /Users/will/Library/Caches/pip/wheels/a8/52/06/7036f638621659c029a526e3fc3199812a4fbec624371adbab
  Building wheel for mpmath (setup.py) ... done
  Created wheel for mpmath: filename=mpmath-1.1.0-cp37-none-any.whl size=532240 sha256=3e054c66d2b974736384729bb28bc3f82e3837e14c8ac199121a41af43e1d97c
  Stored in directory: /Users/will/Library/Caches/pip/wheels/63/9d/8e/37c3f6506ed3f152733a699e92d8e0c9f5e5f01dea262f80ad
Successfully built svgmanip mpmath
Installing collected packages: svgutils, mpmath, ensure, svgmanip
Successfully installed ensure-1.0.0 mpmath-1.1.0 svgmanip-0.0.6 svgutils-0.3.1
will:Ganymede:~% python3
Python 3.7.5 (default, Nov  1 2019, 02:16:32) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import svgmanip
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'svgmanip'
>>> from svgmanip import Element
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'svgmanip'
>>> 
```

**Comment by CrazyPython** [comment]
Hmm, try `import mpmath`. Does that work? This will help debug your environment.

**Comment by vilhelmen** [comment]
`mpmath`, `svgutils`, and `ensure` all import without issue.

**Comment by vilhelmen** [comment]
I did a look into my site-packages directory and there's nothing there for svgmanip? There's a `svgmanip-0.0.6.dist-info` dir but no actual svgmanip. The RECORD file doesn't indicate that anything was actually installed?

```
% cat svgmanip-0.0.6.dist-info/RECORD 
svgmanip-0.0.6.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
svgmanip-0.0.6.dist-info/METADATA,sha256=BV-H6W7WLtETslwsCKSUhB9eEnl2g6Xi2gzoq8Uk-Ig,1596
svgmanip-0.0.6.dist-info/RECORD,,
svgmanip-0.0.6.dist-info/WHEEL,sha256=8zNYZbwQSXoB9IfXOjPfeNwvAsALAjffgk27FqvCWbo,110
svgmanip-0.0.6.dist-info/top_level.txt,sha256=tVkELi0Guo_3Kj4L1I5QyNTem1XIHYsEhJ4ZhZaJYik,9
```

**Comment by CrazyPython** [comment]
Fixed. `from svgmanip import Element` now works.
